=== yosoytony64/NCA-Desafio-CSI1-Equipo2/ASIGNATURAS/Lenguaje_de_Marcas/datos/Excel_Desafio.dtd
<!ELEMENT root (row+)>

<!ELEMENT row (
    ID,
    Nombre,
    Raza,
    Edad,
    Color,
    Altura_cm,
    Peso_kg,
    País_Origen,
    Disciplina,
    Precio_EUR,
    Foto
)>

<!ELEMENT ID (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Raza (#PCDATA)>
<!ELEMENT Edad (#PCDATA)>
<!ELEMENT Color (#PCDATA)>
<!ELEMENT Altura_cm (#PCDATA)>
<!ELEMENT Peso_kg (#PCDATA)>
<!ELEMENT País_Origen (#PCDATA)>
<!ELEMENT Disciplina (#PCDATA)>
<!ELEMENT Precio_EUR (#PCDATA)>
<!ELEMENT Foto (#PCDATA)>

=== yosoytony64/NCA-Desafio-CSI1-Equipo2/ASIGNATURAS/Lenguaje_de_Marcas/datos/Excel_Desafio - Hoja 1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "Excel_Desafio.dtd">
<root>
  <row>
    <ID>1</ID>
    <Nombre>Relámpago</Nombre>
    <Raza>Andaluz</Raza>
    <Edad>5</Edad>
    <Color>Negro</Color>
    <Altura_cm>165</Altura_cm>
    <Peso_kg>520</Peso_kg>
    <País_Origen>España</País_Origen>
    <Disciplina>Doma</Disciplina>
    <Precio_EUR>12000</Precio_EUR>
    <Foto>caballo1.jpg</Foto>
  </row>
  <row>
    <ID>2</ID>
    <Nombre>Trueno</Nombre>
    <Raza>Árabe</Raza>
    <Edad>7</Edad>
    <Color>Blanco</Color>
    <Altura_cm>155</Altura_cm>
    <Peso_kg>430</Peso_kg>
    <País_Origen>Arabia Saudí</País_Origen>
    <Disciplina>Resistencia</Disciplina>
    <Precio_EUR>15000</Precio_EUR>
    <Foto>caballo2.jpg</Foto>
  </row>
  <row>
    <ID>3</ID>
    <Nombre>Centella</Nombre>
    <Raza>Frisón</Raza>
    <Edad>6</Edad>
    <Color>Negro</Color>
    <Altura_cm>170</Altura_cm>
    <Peso_kg>600</Peso_kg>
    <País_Origen>Países Bajos</País_Origen>
    <Disciplina>Exhibición</Disciplina>
    <Precio_EUR>18000</Precio_EUR>
    <Foto>caballo3.jpg</Foto>
  </row>
  <row>
    <ID>4</ID>
    <Nombre>Sultán</Nombre>
    <Raza>Pura Sangre</Raza>
    <Edad>4</Edad>
    <Color>Castaño</Color>
    <Altura_cm>168</Altura_cm>
    <Peso_kg>500</Peso_kg>
    <País_Origen>Reino Unido</País_Origen>
    <Disciplina>Carreras</Disciplina>
    <Precio_EUR>22000</Precio_EUR>
    <Foto>caballo4.jpg</Foto>
  </row>
  <row>
    <ID>5</ID>
    <Nombre>Nevada</Nombre>
    <Raza>Appaloosa</Raza>
    <Edad>8</Edad>
    <Color>Moteado</Color>
    <Altura_cm>160</Altura_cm>
    <Peso_kg>510</Peso_kg>
    <País_Origen>Estados Unidos</País_Origen>
    <Disciplina>Paseo</Disciplina>
    <Precio_EUR>9000</Precio_EUR>
    <Foto>caballo5.jpg</Foto>
  </row>
  <row>
    <ID>6</ID>
    <Nombre>Pegaso</Nombre>
    <Raza>Lusitano</Raza>
    <Edad>9</Edad>
    <Color>Gris</Color>
    <Altura_cm>164</Altura_cm>
    <Peso_kg>540</Peso_kg>
    <País_Origen>Portugal</País_Origen>
    <Disciplina>Doma</Disciplina>
    <Precio_EUR>16000</Precio_EUR>
    <Foto>caballo6.jpg</Foto>
  </row>
  <row>
    <ID>7</ID>
    <Nombre>Tormenta</Nombre>
    <Raza>Percherón</Raza>
    <Edad>10</Edad>
    <Color>Gris</Color>
    <Altura_cm>180</Altura_cm>
    <Peso_kg>850</Peso_kg>
    <País_Origen>Francia</País_Origen>
    <Disciplina>Trabajo</Disciplina>
    <Precio_EUR>14000</Precio_EUR>
    <Foto>caballo7.jpg</Foto>
  </row>
  <row>
    <ID>8</ID>
    <Nombre>Valiente</Nombre>
    <Raza>Mustang</Raza>
    <Edad>5</Edad>
    <Color>Marrón</Color>
    <Altura_cm>158</Altura_cm>
    <Peso_kg>480</Peso_kg>
    <País_Origen>Estados Unidos</País_Origen>
    <Disciplina>Western</Disciplina>
    <Precio_EUR>11000</Precio_EUR>
    <Foto>caballo8.jpg</Foto>
  </row>
  <row>
    <ID>9</ID>
    <Nombre>Rocinante</Nombre>
    <Raza>Haflinger</Raza>
    <Edad>12</Edad>
    <Color>Rubio</Color>
    <Altura_cm>150</Altura_cm>
    <Peso_kg>450</Peso_kg>
    <País_Origen>Austria</País_Origen>
    <Disciplina>Paseo</Disciplina>
    <Precio_EUR>7000</Precio_EUR>
    <Foto>caballo9.jpg</Foto>
  </row>
  <row>
    <ID>10</ID>
    <Nombre>Eclipse</Nombre>
    <Raza>Árabe</Raza>
    <Edad>6</Edad>
    <Color>Negro</Color>
    <Altura_cm>154</Altura_cm>
    <Peso_kg>420</Peso_kg>
    <País_Origen>Egipto</País_Origen>
    <Disciplina>Resistencia</Disciplina>
    <Precio_EUR>15500</Precio_EUR>
    <Foto>caballo10.jpg</Foto>
  </row>
  <row>
    <ID>11</ID>
    <Nombre>Cometa</Nombre>
    <Raza>Andaluz</Raza>
    <Edad>7</Edad>
    <Color>Blanco</Color>
    <Altura_cm>166</Altura_cm>
    <Peso_kg>530</Peso_kg>
    <País_Origen>España</País_Origen>
    <Disciplina>Doma</Disciplina>
    <Precio_EUR>12500</Precio_EUR>
    <Foto>caballo11.jpg</Foto>
  </row>
  <row>
    <ID>12</ID>
    <Nombre>Bandido</Nombre>
    <Raza>Mustang</Raza>
    <Edad>9</Edad>
    <Color>Castaño</Color>
    <Altura_cm>159</Altura_cm>
    <Peso_kg>490</Peso_kg>
    <País_Origen>Estados Unidos</País_Origen>
    <Disciplina>Western</Disciplina>
    <Precio_EUR>9800</Precio_EUR>
    <Foto>caballo12.jpg</Foto>
  </row>
  <row>
    <ID>13</ID>
    <Nombre>Niebla</Nombre>
    <Raza>Frisón</Raza>
    <Edad>8</Edad>
    <Color>Negro</Color>
    <Altura_cm>172</Altura_cm>
    <Peso_kg>610</Peso_kg>
    <País_Origen>Países Bajos</País_Origen>
    <Disciplina>Exhibición</Disciplina>
    <Precio_EUR>17500</Precio_EUR>
    <Foto>caballo13.jpg</Foto>
  </row>
  <row>
    <ID>14</ID>
    <Nombre>Fuego</Nombre>
    <Raza>Pura Sangre</Raza>
    <Edad>3</Edad>
    <Color>Alazán</Color>
    <Altura_cm>167</Altura_cm>
    <Peso_kg>495</Peso_kg>
    <País_Origen>Irlanda</País_Origen>
    <Disciplina>Carreras</Disciplina>
    <Precio_EUR>24000</Precio_EUR>
    <Foto>caballo14.jpg</Foto>
  </row>
  <row>
    <ID>15</ID>
    <Nombre>Dólar</Nombre>
    <Raza>Appaloosa</Raza>
    <Edad>6</Edad>
    <Color>Moteado</Color>
    <Altura_cm>161</Altura_cm>
    <Peso_kg>505</Peso_kg>
    <País_Origen>Canadá</País_Origen>
    <Disciplina>Paseo</Disciplina>
    <Precio_EUR>9200</Precio_EUR>
    <Foto>caballo15.jpg</Foto>
  </row>
  <row>
    <ID>16</ID>
    <Nombre>Noble</Nombre>
    <Raza>Lusitano</Raza>
    <Edad>11</Edad>
    <Color>Gris</Color>
    <Altura_cm>165</Altura_cm>
    <Peso_kg>545</Peso_kg>
    <País_Origen>Portugal</País_Origen>
    <Disciplina>Doma</Disciplina>
    <Precio_EUR>15800</Precio_EUR>
    <Foto>caballo16.jpg</Foto>
  </row>
  <row>
    <ID>17</ID>
    <Nombre>Titán</Nombre>
    <Raza>Percherón</Raza>
    <Edad>13</Edad>
    <Color>Negro</Color>
    <Altura_cm>182</Altura_cm>
    <Peso_kg>870</Peso_kg>
    <País_Origen>Francia</País_Origen>
    <Disciplina>Trabajo</Disciplina>
    <Precio_EUR>14500</Precio_EUR>
    <Foto>caballo17.jpg</Foto>
  </row>
  <row>
    <ID>18</ID>
    <Nombre>Ciclón</Nombre>
    <Raza>Árabe</Raza>
    <Edad>5</Edad>
    <Color>Blanco</Color>
    <Altura_cm>156</Altura_cm>
    <Peso_kg>425</Peso_kg>
    <País_Origen>Emiratos Árabes</País_Origen>
    <Disciplina>Resistencia</Disciplina>
    <Precio_EUR>16200</Precio_EUR>
    <Foto>caballo18.jpg</Foto>
  </row>
  <row>
    <ID>19</ID>
    <Nombre>Brisa</Nombre>
    <Raza>Haflinger</Raza>
    <Edad>7</Edad>
    <Color>Rubio</Color>
    <Altura_cm>149</Altura_cm>
    <Peso_kg>440</Peso_kg>
    <País_Origen>Austria</País_Origen>
    <Disciplina>Paseo</Disciplina>
    <Precio_EUR>6800</Precio_EUR>
    <Foto>caballo19.jpg</Foto>
  </row>
  <row>
    <ID>20</ID>
    <Nombre>Faraón</Nombre>
    <Raza>Andaluz</Raza>
    <Edad>8</Edad>
    <Color>Gris</Color>
    <Altura_cm>167</Altura_cm>
    <Peso_kg>535</Peso_kg>
    <País_Origen>España</País_Origen>
    <Disciplina>Doma</Disciplina>
    <Precio_EUR>13000</Precio_EUR>
    <Foto>caballo20.jpg</Foto>
  </row>
  <row>
    <ID>21</ID>
    <Nombre>Zeus</Nombre>
    <Raza>Frisón</Raza>
    <Edad>6</Edad>
    <Color>Negro</Color>
    <Altura_cm>171</Altura_cm>
    <Peso_kg>605</Peso_kg>
    <País_Origen>Países Bajos</País_Origen>
    <Disciplina>Exhibición</Disciplina>
    <Precio_EUR>18200</Precio_EUR>
    <Foto>caballo21.jpg</Foto>
  </row>
  <row>
    <ID>22</ID>
    <Nombre>Apolo</Nombre>
    <Raza>Pura Sangre</Raza>
    <Edad>4</Edad>
    <Color>Marrón</Color>
    <Altura_cm>169</Altura_cm>
    <Peso_kg>510</Peso_kg>
    <País_Origen>Reino Unido</País_Origen>
    <Disciplina>Carreras</Disciplina>
    <Precio_EUR>22500</Precio_EUR>
    <Foto>caballo22.jpg</Foto>
  </row>
  <row>
    <ID>23</ID>
    <Nombre>Luna</Nombre>
    <Raza>Appaloosa</Raza>
    <Edad>9</Edad>
    <Color>Blanco</Color>
    <Altura_cm>160</Altura_cm>
    <Peso_kg>500</Peso_kg>
    <País_Origen>Estados Unidos</País_Origen>
    <Disciplina>Paseo</Disciplina>
    <Precio_EUR>9100</Precio_EUR>
    <Foto>caballo23.jpg</Foto>
  </row>
  <row>
    <ID>24</ID>
    <Nombre>Rey</Nombre>
    <Raza>Lusitano</Raza>
    <Edad>10</Edad>
    <Color>Gris</Color>
    <Altura_cm>166</Altura_cm>
    <Peso_kg>550</Peso_kg>
    <País_Origen>Portugal</País_Origen>
    <Disciplina>Doma</Disciplina>
    <Precio_EUR>16500</Precio_EUR>
    <Foto>caballo24.jpg</Foto>
  </row>
  <row>
    <ID>25</ID>
    <Nombre>Hércules</Nombre>
    <Raza>Percherón</Raza>
    <Edad>12</Edad>
    <Color>Gris</Color>
    <Altura_cm>181</Altura_cm>
    <Peso_kg>860</Peso_kg>
    <País_Origen>Francia</País_Origen>
    <Disciplina>Trabajo</Disciplina>
    <Precio_EUR>14800</Precio_EUR>
    <Foto>caballo25.jpg</Foto>
  </row>
  <row>
    <ID>26</ID>
    <Nombre>Destello</Nombre>
    <Raza>Mustang</Raza>
    <Edad>5</Edad>
    <Color>Negro</Color>
    <Altura_cm>157</Altura_cm>
    <Peso_kg>475</Peso_kg>
    <País_Origen>Estados Unidos</País_Origen>
    <Disciplina>Western</Disciplina>
    <Precio_EUR>10200</Precio_EUR>
    <Foto>caballo26.jpg</Foto>
  </row>
  <row>
    <ID>27</ID>
    <Nombre>Arena</Nombre>
    <Raza>Haflinger</Raza>
    <Edad>8</Edad>
    <Color>Rubio</Color>
    <Altura_cm>151</Altura_cm>
    <Peso_kg>448</Peso_kg>
    <País_Origen>Austria</País_Origen>
    <Disciplina>Paseo</Disciplina>
    <Precio_EUR>7200</Precio_EUR>
    <Foto>caballo27.jpg</Foto>
  </row>
  <row>
    <ID>28</ID>
    <Nombre>Sol</Nombre>
    <Raza>Árabe</Raza>
    <Edad>6</Edad>
    <Color>Alazán</Color>
    <Altura_cm>155</Altura_cm>
    <Peso_kg>430</Peso_kg>
    <País_Origen>Qatar</País_Origen>
    <Disciplina>Resistencia</Disciplina>
    <Precio_EUR>15100</Precio_EUR>
    <Foto>caballo28.jpg</Foto>
  </row>
  <row>
    <ID>29</ID>
    <Nombre>Imperial</Nombre>
    <Raza>Andaluz</Raza>
    <Edad>9</Edad>
    <Color>Blanco</Color>
    <Altura_cm>168</Altura_cm>
    <Peso_kg>540</Peso_kg>
    <País_Origen>España</País_Origen>
    <Disciplina>Doma</Disciplina>
    <Precio_EUR>13500</Precio_EUR>
    <Foto>caballo29.jpg</Foto>
  </row>
  <row>
    <ID>30</ID>
    <Nombre>Ébano</Nombre>
    <Raza>Frisón</Raza>
    <Edad>7</Edad>
    <Color>Negro</Color>
    <Altura_cm>173</Altura_cm>
    <Peso_kg>615</Peso_kg>
    <País_Origen>Países Bajos</País_Origen>
    <Disciplina>Exhibición</Disciplina>
